server:
  port: 8072

spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://configserver:8071/"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
