server:
  port: 8761

spring:
  config:
    import: "optional:configserver:http://configserver:8071/"

eureka:
  instance:
    hostname: eurekaserver
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
