server:
  port: 8072

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true
